version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gif-generator"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-tsljwszxn1ow"
s3_prefix = "gif-generator"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DomainName=\"gif-generator-local.rdok.co.uk\" Route53HostedZoneId=\"ZSY7GT2NEDPN0\" WildcardCertificateARN=\"arn:aws:acm:us-east-1:353196159109:certificate/b7e23fbf-69a3-440f-8560-59f240f2cc09\""

